### ISSUE TITLE
Ensure "force" parameter of DOMTokenList.toggle is supported

### ISSUE THREAD

**Issue by Alhadis** [Alhadis/DOMTokenList-Polyfill#6]
IE10+ lacks support for the optional second parameter of DOMTokenList's `.toggle` method, meaning conditionally setting a class requires something like `element.classList[ test ? "add" : "remove"]("class-name");` or something similarly asinine.

**Comment by ganlanyuan** [comment]
I tested in IE 10 and 11 with this code:

```
var firstEl = document.querySelector('.first');
var abc = 99;
firstEl.classList.toggle('bold', abc > 100); // bold was added
```

Seems they didn't work.

**Comment by Alhadis** [comment]
@ganlanyuan: I can't reproduce this; can you confirm whether the script is being loaded asynchronously, or being loaded after you're attempting to manipulate classes?

**Comment by Alhadis** [comment]
@ganlanyuan [Is this](https://github.com/ganlanyuan/go-native/blob/master/bower.json) what you're having trouble with?

``` json
"devDependencies": {
    "classlist": "^2014.12.13",
    "fix-ie": "^1.2.0",
    "domtokenlist": "^1.0.0",
    "es5-shim": "^4.5.7"
}
```

You can drop `classlist` from your `devDependencies` list, since DOMTokenList already handles that for you. Also, `fix-ie` already comes bundled with `domtokenlist`, so there's no point including `domtokenlist` separately:

``` json
"devDependencies": {
    "fix-ie": "^1.2.0",
    "es5-shim": "^4.5.7"
}
```

**Comment by ganlanyuan** [comment]
"force" parameter works well on IE 10 & 11 now, thanks!

**Comment by Alhadis** [comment]
Good to hear! :) You're welcome, mate. ^^
